"""criando senha na tabela validando

Revision ID: 02740e4922a9
Revises: 88abb4cc1274
Create Date: 2025-01-20 21:28:10.900576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02740e4922a9'
down_revision: Union[str, None] = '88abb4cc1274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
